#!/usr/bin/env bash
set -e -o pipefail

cd "$(dirname "$0")"

default_cmd="./run_generate"

run_args=(-it --rm
    $DOCKER_RUN_ARGS
    --gpus=all
    --ipc=host --ulimit memlock=-1 --ulimit stack=67108864
    -v $PWD:/workdir
    -e sz -e cfg -e ckpt
    vortex
    ${@:-$default_cmd}
)

docker build -t vortex $DOCKER_BUILD_ARGS .
docker run --entrypoint "" "${run_args[@]}"
