#!/usr/bin/env bash
set -e -o pipefail

if [ "$sz" == "7" ]; then
    cfg=${cfg:-configs/shc-evo2-7b-8k-2T-v2-interleave.yml}
    ckpt=${ckpt:-iter_500000.pt}
else
    cfg=${cfg:-configs/shc-evo2-40b-8k-11T-v2.yml}
    ckpt=${ckpt:-iter_504000.pt}
fi

if [ -e "$ckpt" ]; then
    ckpt="--checkpoint_path $ckpt"
else
    echo Using random weights
    ckpt="--dry_run"
fi

python3 generate.py $ckpt --config_path $cfg --debug
