#!/usr/bin/env bash
set -e -o pipefail

cd "$(dirname "$0")"

if [ "$sz" == "7" ]; then
    cfg=${cfg:-configs/evo2-7b-1m.yml}
    ckpt=${ckpt:-evo2_7b.pt}
else
    cfg=${cfg:-configs/evo2-40b-1m.yml}
    ckpt=${ckpt:-evo2_40b.pt}
fi

if [ -e "$ckpt" ]; then
    ckpt="--checkpoint_path $ckpt"
else
    echo Using random weights
    ckpt="--dry_run"
fi

python3 generate.py $ckpt --config_path $cfg --debug
